%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "1064 nm";
opts.DataRange = "C3:F33";

% Specify column names and types
opts.VariableNames = ["wl", "r_un", "r_s", "r_p"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
k13 = readtable("..\data\nb1-k13_nb07-k13_raw_data.xlsx", opts, "UseExcel", false);

%% Clear temporary variables
clear opts

notEmpty = not(isnan(k13.r_un));

X1 = k13.wl;
YMatrix1 = [k13.r_s,k13.r_p];
X2 = k13.wl(notEmpty);
Y1 = k13.r_un(notEmpty);

createfigure(X1, YMatrix1, X2, Y1)

%% PLOTS
function createfigure(X1, YMatrix1, X2, Y1)
%CREATEFIGURE(X1, YMatrix1, X2, Y1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 11-May-2026 11:26:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','S-pol');
set(plot1(2),'DisplayName','P-pol');

% Create plot
plot(X2,Y1,'DisplayName','Unpol');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeast');
ylim([98.6 99.6])
ylabel('Reflectivity [%]')
xlabel('Wavelength [nm]')

% Create xline
xline(1064,'DisplayName','Nd:YAG','Parent',axes1,'Label','Nd:YAG');

title('K13 Dieclectric Mirror Reflectivity')

end